version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak123
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    command:
      - start-dev

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

  jasperreports:
    image: retriever/jasperserver:latest
    container_name: jasperreports
    restart: always
    depends_on:
      - postgres
    environment:
      # --- Connexion à PostgreSQL existant ---
      DB_TYPE: postgresql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: jasperdb
      DB_USER: jasper
      DB_PASSWORD: jasper123

      # --- Compte JasperServer ---
      JASPERSERVER_USER: jasperadmin
      JASPERSERVER_PASSWORD: jasperadmin
    ports:
      - "8082:8080"
    volumes:
      - jasper_data:/usr/local/tomcat/webapps/jasperserver
    networks:
      - default

volumes:
  postgres_data:
  jasper_data:
